// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69AESBPw7O1GV077PLktuiQBx1-oDTdM',
    appId: '1:153126438486:web:c88ec1b041cbd566f21df7',
    messagingSenderId: '153126438486',
    projectId: 'hamro-dokan-6f4be',
    authDomain: 'hamro-dokan-6f4be.firebaseapp.com',
    storageBucket: 'hamro-dokan-6f4be.firebasestorage.app',
    measurementId: 'G-RMLVGME40S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhy9oCcyAs45Hm0ld58g_PpSuMBZOMlY',
    appId: '1:153126438486:android:07dc183e6e14a069f21df7',
    messagingSenderId: '153126438486',
    projectId: 'hamro-dokan-6f4be',
    storageBucket: 'hamro-dokan-6f4be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjcgZxOVt-SMwaV_JUoT01Zmw6XpyORjA',
    appId: '1:153126438486:ios:87c55777de2dcbaff21df7',
    messagingSenderId: '153126438486',
    projectId: 'hamro-dokan-6f4be',
    storageBucket: 'hamro-dokan-6f4be.firebasestorage.app',
    iosBundleId: 'com.codingwitht.ecommerce.tstoreEcommerceApp',
  );

}